theme: jekyll-theme-modernist
title: Machine Learning for Physical Science and Engineering Seminar at UNH
description: Here you can find all the files for UNH Machine Learning for Physical Science and Engineering Seminar Series
include: *.ipynb
(https://github.com/chapmanlab/ML/raw/master/ML_seminar_1_LinearRegression.ipynb)
